//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by VecDemo.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_SHAPESBOX                   103
#define IDR_MAINFRAME                   128
#define IDR_ITEM_MENU                   140
#define IDR_TOOLBOX                     147
#define IDR_TOOLBAR_PAGE                159
#define IDR_TOOLBAR_OBJECT              163
#define IDD_LINE_TYPE                   184
#define IDD_EDIT_TEXT                   189
#define IDD_SHAPE_FILL                  190
#define IDD_ROTATE_FREE                 193
#define IDD_PAGE_BACKGROUND             194
#define IDD_PAGE_TYPE                   199
#define IDB_PAGE_PORT                   249
#define IDB_PAGE_LAND                   252
#define IDD_PICTURE_SIZE                259
#define IDD_GRID_PROP                   270
#define IDB_SHAPES_BITMAP               718
#define IDR_TOOLBAR_ALIGN               719
#define IDD_SHADOW_DLG                  722
#define IDD_PIC_TRANSPARENT_DLG         763
#define IDC_LINE_STYLE                  1002
#define IDAPPLY                         1003
#define IDC_FILL_PATTERN                1004
#define IDC_WIDTH                       1018
#define IDC_HEIGHT                      1019
#define IDC_LINE_WIDTH                  1023
#define IDC_EDIT1                       1024
#define IDC_FILL_MODE                   1025
#define IDC_EDIT2                       1030
#define IDC_SPIN1                       1032
#define IDC_BGIMG_RADIO                 1033
#define IDC_SOLIDCOL_RADIO              1034
#define IDC_BACK_IMAGE_BROWSE           1038
#define IDC_PAGE_SIZE_COMBO             1070
#define IDC_PORTRAIT_RADIO              1071
#define IDC_LANDSCAPE_RADIO             1072
#define IDC_PREVIEW                     1076
#define IDC_WIDTH_UNITS                 1086
#define IDC_HEIGHT_UNITS                1087
#define IDC_PROPORTIONS                 1088
#define IDC_IS_TRANSPARENT              1091
#define IDC_BUTTON_FILEOPEN             1113
#define IDC_COLOR_BUTTON                1114
#define IDC_USE_SHADOW                  1124
#define IDC_ROP2                        1125
#define ID_TOOL_SELECT                  33794
#define ID_TOOL_DRAG_DROP               33795
#define ID_TOOL_ROTATE                  33796
#define ID_TOOL_TEXT                    33797
#define ID_TOOL_LINE                    33798
#define ID_TOOL_ELLIPSE                 33799
#define ID_TOOL_RECT                    33800
#define ID_TOOL_POLYLINE                33801
#define ID_TOOL_POLYGON                 33802
#define ID_TOOL_FREEHAND                33803
#define ID_TOOL_FREEHAND_CLOSED         33804
#define ID_TOOL_SHAPE                   33805
#define ID_PAGE_BACKGROUND              33806
#define ID_PAGE_RESETZOOM               33808
#define ID_PAGE_FITTOWINDOW             33809
#define ID_LINE_LINE                    42778
#define ID_EDIT_DELETE                  42791
#define ID_EDIT_SELECTALL               42792
#define ID_TOOL_ZOOM_RECT               42804
#define ID_TOOL_PANIMAGE                42805
#define ID_PAGE_ZOOMIN                  42832
#define ID_PAGE_ZOOMOUT                 42833
#define ID_TEXT_EDITTEXT                42835
#define ID_TEXT_BACKCOLOR               42836
#define ID_TEXT_FORECOLOR               42837
#define ID_TEXT_FILL                    42838
#define ID_TEXT_BORDERFRAME             42839
#define ID_TEXT_FONT                    42840
#define ID_SHAPE_FILL                   42841
#define ID_SHAPE_BACKCOLOR              42842
#define ID_SHAPE_FORECOLOR              42843
#define ID_LINE_BACKCOLOR               42844
#define ID_LINE_FORECOLOR               42845
#define ID_SHAPE_BORDERFRAME            42847
#define ID_ORDER_SENDTOBACK             42848
#define ID_ORDER_BRINGTOFRONT           42849
#define ID_PICTURE_CROP_RECTANGLE       42850
#define ID_PICTURE_CROP_ELLIPSE         42851
#define ID_PICTURE_ROTATE_90CW          42852
#define ID_PICTURE_ROTATE_90CCW         42853
#define ID_PICTURE_ROTATE_180           42854
#define ID_PICTURE_ROTATE_FREE          42855
#define ID_PICTURE_FLIP_VERTICAL        42856
#define ID_PICTURE_FLIP_HORIZONTAL      42857
#define ID_PAGE_FITTOWIDTH              42861
#define ID_PAGE_FITTOHEIGHT             42862
#define ID_VIEW_TOOLBARS_STANDARD       42863
#define ID_VIEW_TOOLBARS_OBJECT         42864
#define ID_VIEW_TOOLBARS_PAGE           42865
#define ID_VIEW_TOOLBARS_ALIGN          42866
#define ID_VIEW_TOOLBARS_TOOLBOX        42867
#define ID_LISTMENU_REFRESH             42878
#define ID_OBJECT_BACKCOLOR             42879
#define ID_OBJECT_FORECOLOR             42880
#define ID_APSPAGEMENU_RENAMEPAGE       42891
#define ID_FILE_PRINT_DISABLE           42894
#define ID_FILE_PRINT_PREVIEW_DISABLE   42895
#define ID_FILE_PRINT_SETUP_DISABLE     42896
#define ID_PICTURE_SIZE                 42898
#define ID_APSPAGEMENU_RENAMEPAGEF2     -22631
#define ID_VIEW_RULLERS                 42909
#define ID_VIEW_GUIDES                  42910
#define ID_VIEW_GRID                    42911
#define ID_VIEW_SNAP2GUIDES             42912
#define ID_VIEW_SNAP2GRID               42913
#define ID_VIEW_GRID_PROPERTIES         42914
#define ID_ORDER_SENDONEBACK            42915
#define ID_ORDER_SENDONEFORE            42916
#define ID_GROUP_GROUP                  42917
#define ID_GROUP_UNGROUP                42918
#define ID_PICTURE_CROP_POLYGON         42919
#define ID_PICTURE_CROP_FREEHAND        42920
#define ID_PICTURE_CROP_SHAPE           42921
#define ID_VIEW_LOCK_GUIDES             42925
#define ID_OBJECT_TEXT_ALIGNLEFT        42926
#define ID_OBJECT_TEXT_ALIGNCENTER      42927
#define ID_OBJECT_TEXT_ALIGNRIGHT       42928
#define ID_OBJECT_ALIGN_LEFT            42938
#define ID_OBJECT_ALIGN_CENTER          42939
#define ID_OBJECT_ALIGN_RIGHT           42940
#define ID_OBJECT_ALIGN_TOP             42941
#define ID_OBJECT_ALIGN_MIDDLE          42942
#define ID_OBJECT_ALIGN_BOTTOM          42943
#define ID_OBJECT_ALIGN_DISTRIBUTEHORIZONTALLY 42944
#define ID_OBJECT_ALIGN_DISTRIBUTEVERTICALLY 42945
#define ID_OBJECT_ALIGN_LOCKOBJECT      42947
#define ID_OBJECT_ALIGN_UNLOCK          42958
#define ID_PICMAPPING_REMOVEPHOTO       42959
#define ID_PICMAPPING_RESETMAPPINGAREA  42960
#define ID_SHAPE_SHOWPOINTS             42961
#define ID_OBJECT_PICTURE_SHADOW        42967
#define ID_CREATE_FRAME                 42989
#define ID_OBJECT_PICTURE_TRANSPARENCY  42991
#define IDS_GRID_TOO_SMALL              59164

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        773
#define _APS_NEXT_COMMAND_VALUE         43021
#define _APS_NEXT_CONTROL_VALUE         1141
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
